Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')

env.AppendUnique(CPPDEFINES = [ 'INSTALLERBUNDLE_LIBRARY' ])

# Sigh
env['CPPPATH'] += [ '.' ]

env.RequireLibraries('uibase')

lib = env.SharedLibrary('installerBundle', env.Glob('*.cpp'))
env.InstallPlugin(lib)

"""
CONFIG(release, debug|release) {
  QMAKE_CXXFLAGS += /Zi
  QMAKE_LFLAGS += /DEBUG
}

"""
