Import('qt_env')

env = qt_env.Clone()

env.DisableQtModules('Gui')
env.AppendUnique(CPPDEFINES = [ 'INSTALLERBUNDLE_LIBRARY' ])

# Sigh
env['CPPPATH'] += [ '.' ]

lib = env.SharedLibrary('installerBundle', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
